### ISSUE TITLE
使用docker配置HLS无法转码，docker内没有ffmpeg

### ISSUE THREAD

**Issue by a57571735** [ossrs/srs#1523]
**描述**
使用docker配置HLS无法转码，docker内没有ffmpeg

**环境**
1. 操作系统：centos 7
1. SRS版本: ossrs/srs:3

**期望行为**
希望docker能完整支持HLS

**Comment by winlinvip** [comment]
The FFmpeg in [ossrs/srs:dev](https://github.com/ossrs/srs-docker/tree/dev) has been added to Docker, currently version 4.1. Please refer to the usage instructions in [srs-docker](https://github.com/ossrs/srs-docker#ffmpeg).

Comparing the image sizes, SRS is only around 2.6MB, while the compressed image has increased from 74.88MB to 84.194MB, adding 9.314MB. After decompression, the image size has increased from 212MB to 234MB, adding 22MB. I don't know if it's worth it or not 😭.

Layer information is as follows:
![image](https://user-images.githubusercontent.com/2777660/71165945-af4c4b00-228c-11ea-843d-206f86887bd5.png)

Since FFMPEG is frequently updated and sometimes requires the use of a custom version, it is recommended to compile it yourself. You can refer to the [Dockerfile](https://github.com/ossrs/srs-docker/blob/dev/Dockerfile) to build your own FFMPEG. This way, when starting SRS, you can replace the built-in FFMPEG with your own. The method is the same as replacing configuration and log files, just replace the files inside and map the directory `/usr/local/srs/objs/ffmpeg/bin/ffmpeg`.

```
docker run -p 1935:1935 -p 1985:1985 -p 8080:8080 \
    -v /path/of/ffmpeg:/usr/local/srs/objs/ffmpeg/bin/ffmpeg \
    ossrs/srs:3
```

With FFMPEG available in Docker, the configurations in the configuration file that use FFMPEG, such as transcoding and ingest, are now usable.

`TRANS_BY_GPT3`

**Comment by wangjunjx8868** [comment]
> 已经将[ossrs/srs:dev](https://github.com/ossrs/srs-docker/tree/dev)中的FFMEPG，目前是4.1放到了docker中，参考[srs-docker](https://github.com/ossrs/srs-docker#ffmpeg)的使用说明。
> 
> 对比镜像大小，SRS只有2.6MB左右，压缩的镜像是从74.88MB变成84.194MB增加了9.314MB，解压后的镜像从212MB变成234MB增加了22MB，也不知道是否值得 😭
> 
> 层信息如下： ![image](https://user-images.githubusercontent.com/2777660/71165945-af4c4b00-228c-11ea-843d-206f86887bd5.png)
> 
> 由于FFMPEG经常更新，而且有时候需要使用自己的版本，推荐还是自己编译，可以参考[Dockerfile](https://github.com/ossrs/srs-docker/blob/dev/Dockerfile)做自己的FFMPEG。这样就可以启动SRS时，用自己的FFMPEG替换SRS自带的了，方法和替换配置文件和日志文件一样，都是换掉里面的文件，映射下目录`/usr/local/srs/objs/ffmpeg/bin/ffmpeg`就好了：
> 
> ```
> docker run -p 1935:1935 -p 1985:1985 -p 8080:8080 \
>     -v /path/of/ffmpeg:/usr/local/srs/objs/ffmpeg/bin/ffmpeg \
>     ossrs/srs:3
> ```
> 
> 在Docker中有了FFMPEG，那么配置文件中用到FFMPEG的配置，比如转码和ingest都是可用的了。

既然ffmpeg已经集成了，docker 创建容器的时候如何启用 ffmpeg？

**Comment by paranoia-12** [comment]
ffmpeg streaming error: Invalid data found when processing input. How to solve it

`TRANS_BY_GPT3`
