### ISSUE TITLE
通过webrtc推流，然后webrtc拉流会花屏

### ISSUE THREAD

**Issue by flyboyxiang** [ossrs/srs#1867]
SRS版本(Version): `4.0.34`
期望通过webrtc推摄像头，通过webrtc拉流，画面不会花。如果是静止画面还好，手在摄像头来回移动，目前花屏很严重
通过rtmp推摄像头，通过webrtc拉流没有花屏，手来回移动也不会花屏

**Comment by LuluChina** [comment]
I also encountered the same problem on my end. It should be due to the low bitrate of the WEBRTC streaming. In this case, the RTC streaming bitrate quickly decreases to a very low value. By setting x-google-start-bitrate=5000, I set the initial bitrate to 5 Mbps. Through the Chrome WEBRTC debugging page, I noticed that the bitrate keeps decreasing. This decrease is probably not due to network issues because I am testing it on an internal network. The bitrate eventually drops to around 100 Kbps. With such a low bitrate, the moving images will definitely appear pixelated. I'm not sure if it is related to RTCP feedback.

`TRANS_BY_GPT3`

**Comment by flying1314** [comment]
It should be related to RTCP, but it hasn't been fixed yet. Has no one reported the screen flickering?

`TRANS_BY_GPT3`

**Comment by LuluChina** [comment]
> It should be related to RTCP, but it hasn't been fixed yet. Has no one reported the screen flickering?

In srs_app_rtc_conn.cpp, after removing the payload filtering condition, it worked fine. Hope this helps you. The main issue was that the condition was preventing the transmission of transport cc RTCP packets.

`TRANS_BY_GPT3`

**Comment by flying1314** [comment]
Okay, thank you. Give it a try when you have time.

`TRANS_BY_GPT3`

**Comment by flying1314** [comment]
> > It should be related to RTCP, but it hasn't been fixed yet. Has no one reported the screen flickering issue?
> 
> After removing the payload filtering check in srs_app_rtc_conn.cpp, it worked fine. Hope this helps you. The main issue was that the check was preventing the transmission of transport cc RTCP packets.

Hello, may I ask where exactly is this located? Has it been fixed in the new version?

`TRANS_BY_GPT3`
