### ISSUE TITLE
SRS中的GB28181能否实现双向语音对讲？

### ISSUE THREAD

**Issue by ZeroBloodedge** [ossrs/srs#1898]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `4.0.35`
我成功部署了SRS的GB28181服务，目前能够正常听到直播流的声音，但是可不可以从服务器端往摄像头那一端传播声音呢？如果可以的话具体要怎么做？

**Comment by ouzhou** [comment]
This should have corresponding instructions for GB28181, including the PTZ, etc.

`TRANS_BY_GPT3`

**Comment by ZeroBloodedge** [comment]
> This should have corresponding instructions for GB28181, including the PTZ control.

> It seems that GB28181 does not have such voice intercom instructions. I have researched this recently, and there are not many intercoms using GB28181. LiveGBS has achieved this, but it uses a special method of creating additional channels.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
用WebRTC。

**Comment by winlinvip** [comment]
First consider using WebRTC. If WebRTC is deemed too large, or if you need to utilize the capabilities of an existing camera, then you can only use GB Intercom.

However, currently GB is not stable, so new features cannot be added. We have to wait until the bugs are resolved before supporting new functionalities.

How to converge the bugs? It is necessary to delete some less commonly used features. Currently, the bugs in GB are not converging due to too many supported functionalities.

So, let's consider implementing GB intercom after version 5.0.

`TRANS_BY_GPT3`

**Comment by Cyaim** [comment]
GBT 28181-2016 Public Safety Video Surveillance Networking System Information Transmission, Exchange, and Control Technical Requirements, 
9.12 describes the basic requirements and command flow of voice intercom.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
The GB of SRS is a kind of access method. SRS is not intended to be a fully functional GB server, and it needs to be expanded and implemented by oneself.

`TRANS_BY_GPT3`
