### ISSUE TITLE
SRS的SRT压力测试，内存占用很高不释放

### ISSUE THREAD

**Issue by DoItWithMe** [ossrs/srs#1918]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)
在SRT的压力测试中，SRS的内存占用很高且不会释放，同时在测试停止后，SRS日志中仍有大量连接信息在刷新（SRS对SRT
请求的处理有延迟），且在压力测试中，拉取SRT推过来的流有很大的画面延迟。

1. SRS版本(Version): `SRS Release 4.0`

1. SRS的配置如下(Config):
```
vhost __defaultVhost__ {
    
    min_latency     on;
    tcp_nodelay     on;

    publish{
        mr          off;
    }
    play{
        queue_length 10; #跟GOP有关，如果GOP是1秒且queue_length也是1秒，那么就会导致有一秒的数据就清空，会导致跳跃 --> SRS推荐的值是10毫秒
        mw_latency  100; #值越小，性能损失越厉害 --> SRS推荐的值是100毫秒
        gop_cache   off;#off 会增加首帧时间； on 会增加延迟
    }

    forward{
        enabled on;
        destination IP:PORT;
    }
}
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

压力测试是这样进行的，我会每0.1秒启用一个FFmpeg推SRT - TS流至SRS，并在5秒后主动关闭所有的FFmpeg。在FFmpeg都关闭后就进行新一轮的推流（一轮最多200个FFmpeg 推流）。在上诉测试中，我发现十分钟左右，SRS的内存占用值可以达到2.04G（top 中的RES值），并且只要测试不停止，内存占用就会持续上升。在测试停止后，SRS并不会释放内存（最长等过4个小时都不会释放内存）；在压力测试中，我发现从SRS拉的流的延迟会上升（由一秒增至十几秒，二十几秒）；以上现象只在SRS的SRT压力测试中出现，对SRS进行同样的RTMP压力测试并不会这样

**Comment by winlinvip** [comment]
Possible memory leak.

`TRANS_BY_GPT3`

**Comment by runner365** [comment]
@DoItWithMe Hello, the previous issue with a memory leak in the close function has been resolved.
However, I'm not sure if this issue still exists. Can you please share your testing script with me so that I can reproduce it myself?

If there are any issues, you can add me on WeChat: sweibd, and we can directly communicate to resolve them.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed in SRS 5.0
