### ISSUE TITLE
内存泄漏，GMC没有检测出来

### ISSUE THREAD

**Issue by swgzjhz** [ossrs/srs#2226]
描述：
利用GMC对3.0-R3进行编译，运行，最后发现gmc.log没有内存泄漏，实际上是存在的。
# Build SRS with GMC
./configure --with-gperf --with-gmc && make
 
# Start SRS with GMC
env PPROF_PATH=./objs/pprof HEAPCHECK=normal ./objs/srs -c conf/console.conf 2>gmc.log 
 
# Or CTRL+C to stop gmc
killall -2 srs
 
# To analysis memory leak
cat gmc.log

gmc.log内容
WARNING: Perftools heap leak checker is active -- Performance may suffer
Thread finding failed with -1 errno=14
Thread finding callback was interrupted or crashed; can't fix this

期望：
能正常使用gmc工具

**Comment by winlinvip** [comment]
![image](https://user-images.githubusercontent.com/2777660/142517211-dd49baa1-3b34-403d-b3fa-6a47ffe92f79.png)

The tcmalloc version is too old. We are using version 2.1, which is from 2013, 8 years ago.

I tried [heap-checker](https://github.com/ossrs/srs/tree/4.0release/trunk/research/gperftools/heap-checker) but still didn't receive any GMC messages, so it's definitely because the version is too old and it's not working anymore. We need to upgrade gperftools.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
The document has been updated. Make sure to maintain the markdown structure.

This article only describes the usage of the GPERF tool. For a complete performance analysis method, refer to [SRS Performance (CPU) and Memory Optimization Tool Usage](https://www.jianshu.com/p/6d4a89359352). Make sure to maintain the markdown structure.

Valgrind is a very useful memory and CPU analysis tool, and SRS already supports it. Make sure to maintain the markdown structure.

> SRS has examples illustrating how to integrate and call gmc. Please refer to: [research/gperftools/heap-checker](https://github.com/ossrs/srs/tree/4.0release/trunk/research/gperftools/heap-checker)

Make sure to maintain the markdown structure.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Already updated gperftools to 2.9, but GMC still has some issues, refer to #2247.

So I have closed this issue for now, please follow up on #2247.

`TRANS_BY_GPT3`
