### ISSUE TITLE
兼容交通部 JT / T 1078标准

### ISSUE THREAD

**Issue by swwheihei** [ossrs/srs#2293]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)
交通部2016年发布了《JT/T 1078-2016 道路运输车辆卫星定位系统-视频通信协议》，其中也使用RTP封装视频流，但对其格式进行了扩展增加了SIM卡等信息，导致无法进行协议转换。
我可以提供相关标准的PDF文档。

1. SRS版本(Version): `xxxxxx`
1. SRS的日志如下(Log):
```
xxxxxxxxxxxx
```
1. SRS的配置如下(Config):
```
xxxxxxxxxxxx
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `xxxxxx`
1. `xxxxxx`
1. `xxxxxx`

**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)

**Comment by terry8204** [comment]
Work on your own, this is all self-transformation.



---Original Email---
Sender: ***@***.***
Sent: Tuesday, April 20, 2021, 4:50 PM
Recipient: ***@***.***
CC: ***@***.***
Subject: [ossrs/srs] Compatibility with Ministry of Transport JT/T 1078 standard (#2293)




 
Description
  
Please description your issue here:
The Ministry of Transport released the "JT/T 1078-2016 Road Transport Vehicle Satellite Positioning System-Video Communication Protocol" in 2016, which also uses RTP to encapsulate video streams. However, it has extended the format by adding SIM card and other information, making it impossible to perform protocol conversion.
I can provide the PDF document of the relevant standard.
   
SRS version: xxxxxx

SRS log:
 xxxxxxxxxxxx   
SRS configuration:
 xxxxxxxxxxxx  
Replay
  
**How to replay bug?**
   
xxxxxx 

xxxxxx 

xxxxxx 
 
**Expect**
  
**Please describe your expectation**
  
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@terry8204 Agree.
