### ISSUE TITLE
Windows: Support cygwin 64bits, native Windows and IDE

### ISSUE THREAD

**Issue by winlinvip** [ossrs/srs#2532]
# SRS for Windows

SRS 5.0.89+ supports Windows(Cygwin64).

<a name="build"></a>
## [Build from code](#build)

Please install [Cygwin64](https://cygwin.com/install.html).

Install packages `gcc-g++` `make` `automake` `patch` `pkg-config` `tcl` `cmake`, please see [packages](https://github.com/cygwin/cygwin-install-action#parameters).

Build SRS with cygwin terminal:

```bash
git checkout develop
./configure
make
```

If success, there should be a `./objs/srs.exe`

<a name="install"></a>
## [Install from binary](#install)

For each [release](https://github.com/ossrs/srs/releases) of SRS, from SRS 5.0.89, there is always a binary installer of SRS Windows, normally as the artifact of release, which allows you to install and run SRS very easy.

Bellow is some examples, note that you should always use the latest [release](https://github.com/ossrs/srs/releases), not the fixed one:

* [Latest release](https://github.com/ossrs/srs/releases)
* [SRS-Windows-x86_64-5.0.89-setup.exe](https://github.com/ossrs/srs/releases/tag/v5.0.89)
* [SRS-Windows-x86_64-5.0.19-setup.exe](https://github.com/ossrs/srs/releases/tag/v5.0.19)

> Note: SRS 5.0.89+ supports cygwin pipeline, to build and packge automatically by GitHub Actions.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/2777660/202887289-1ddd5af8-c7ae-4ac9-b23c-672d021aa9e5.png">

Run SRS as administrator:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/2777660/202887333-cf825d33-9a07-43e5-a51a-12d53db2a906.png">

Publish to SRS Windows by FFmpeg:

```bash
ffmpeg -re -i ~/srs/doc/source.flv -c copy -f flv rtmp://win11/live/livestream
```

Play by VLC or [srs-player](http://win11:8080/)

<img width="600" alt="image" src="https://user-images.githubusercontent.com/2777660/202887374-4323b61f-debf-4f07-b173-6b11c1f79d15.png">

Most of SRS features are available in Windows, for example, RTMP, HTTP-FLV, HLS, WebRTC, HTTP-API, Prometheus Exporter, etc.

<a name="package"></a>
## [Package by NSIS](#package)

If want to package by [NSIS](https://nsis.sourceforge.io/Download), please run in cygwin terminal:

```bash
"/cygdrive/c/Program Files (x86)/NSIS/makensis.exe" \
    /DSRS_VERSION=$(./objs/srs -v 2>&1) \
    /DCYGWIN_DIR="C:\cygwin64" \
    packaging/nsis/srs.nsi
```

<a name="known-issues"></a>
## [Known Issues](#known-issues)

- [ ] #3251
- [x] #3252
- [ ] #3253
- [x] #3256
- [x] #3322
- [x] #3254

## Links

ST supports windows: https://github.com/ossrs/state-threads/issues/20

Commits about SRS Windows: https://github.com/ossrs/srs-windows/issues/2

Windows docker also works for SRS, however, `srs.exe` is more popular for windows developers.

**Comment by chenjim** [comment]
My environment [WSL](https://docs.microsoft.com/en-us/windows/wsl/install) + Ubuntu should be more efficient than cygwin.

`TRANS_BY_GPT3`

**Comment by 290008282** [comment]
During the SRS installation process, SRS will be added to the Windows environment variables. Users can open the cmd console and directly launch SRS.


How to solve the issue of not adding system environment variables? What variables should be manually added?

`TRANS_BY_GPT3`

**Comment by duliangheng** [comment]
> During the SRS installation process, SRS will be added to the Windows environment variables. Users can directly launch SRS by opening the cmd console.
> 
> How to solve the issue of not adding system environment variables? What variables should be manually added?

> Mine also didn't add environment variables? Does everyone use Windows?

`TRANS_BY_GPT3`

**Comment by duliangheng** [comment]
git checkout feature/windows
./configure
make
请问./configure这个目录在哪里？没有啊

**Comment by 290008282** [comment]
> 

已经放弃了，等待后续更新，目前使用centos比较稳定

**Comment by 290008282** [comment]
> > During the SRS installation process, SRS will be added to the Windows environment variables, allowing users to directly launch SRS by opening the cmd console.
> > What if the system environment variables are not added? How can it be resolved? Manually add which variables?
> 
> Mine also does not have the environment variables added? Does everyone use Windows?
I have already given up and am waiting for future updates. Currently, I find CentOS more stable to use.

`TRANS_BY_GPT3`

**Comment by duliangheng** [comment]
> 



> 

Have you ever compiled a Windows version? When I compile it, it stops executing with an error at 'Building ffmpeg-4-fit'...

`TRANS_BY_GPT3`

**Comment by duliangheng** [comment]
> > > During the SRS installation process, SRS will be added to the Windows environment variables. Users can directly launch SRS by opening the cmd console.
> > > What should I do if I haven't added the system environment variables? How can I manually add the variables?
> > 
> > 
> > I also haven't added the environment variables. Does everyone use Windows?
> > I have already given up and am waiting for future updates. Currently, I find CentOS more stable to use.

Have you ever compiled a Windows version? When I was compiling, I encountered two issues that prevented me from proceeding...

First issue: ./config
Building libsrtp-2-fit.
patching file crypto/math/datatypes.c
Reversed (or previously applied) patch detected!  Assume -R? [n]

This place, I don't know how to handle it?

Secondly, during the process of making.
In file included from src/app/srs_app_threads.cpp:21:
src/app/srs_app_rtc_dtls.hpp:16:10: fatal error: srtp2/srtp.h: No such file or directory
   16 | #include <srtp2/srtp.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.

That's the end here.


`TRANS_BY_GPT3`

**Comment by duliangheng** [comment]
> 那请问你有编译过windows版本吗？我编译的时候，遇到两个问题执行不下去了。。。
> 
> 第一个： ./config Building libsrtp-2-fit. patching file crypto/math/datatypes.c Reversed (or previously applied) patch detected! Assume -R? [n]
> 
> 这个地方，不知道应该怎么处理？
> 
> 第二个： make的时候 In file included from src/app/srs_app_threads.cpp:21: src/app/srs_app_rtc_dtls.hpp:16:10: fatal error: srtp2/srtp.h: No such file or directory 16 | #include <srtp2/srtp.h> | ^~~~~~~~~~~~~~ compilation terminated.
> 
> 到这儿就结束了。



> > > SRS 安装过程中，会把SRS放到Windows的环境变量中，用户打开cmd控制台，直接可以调起来SRS。
> > > 没有添加系统环境变量怎么解决？手动添加什么变量？
> > 
> > 
> > 我的也没有添加环境变量？每人使用windows吗？
> > 已经放弃了，等待后续更新，目前使用centos比较稳定

那请问你有编译过windows版本吗？我编译的时候，遇到两个问题执行不下去了。。。

第一个： ./config
Building libsrtp-2-fit.
patching file crypto/math/datatypes.c
Reversed (or previously applied) patch detected! Assume -R? [n]

这个地方，不知道应该怎么处理？

第二个： make的时候
In file included from src/app/srs_app_threads.cpp:21:
src/app/srs_app_rtc_dtls.hpp:16:10: fatal error: srtp2/srtp.h: No such file or directory
16 | #include <srtp2/srtp.h>
| ^~~~~~~~~~~~~~
compilation terminated.

到这儿就结束了。

**Comment by 290008282** [comment]
I have not compiled the Windows version before. The actual released version can run normally, but there are some differences in the command slashes (\ and /) compared to the tutorial. My problem at that time was that the conf file configured in Linux could not run properly in the Windows version. 

So I found an old computer and set up a local Linux server with the help of Baota. It's very convenient. Why do we have to use Windows? I don't know what your application environment is, but I use the Linux version to convert RTSP from an internal network camera to RTMP+.flv for external live streaming. It is very stable, and I haven't made any changes since I set it up. The speed is also good, and you can directly upload the public network service to the cloud. Lightweight servers are not expensive nowadays.




L.HF
***@***.***

Rongcheng Yijie Network Technology Co., Ltd.


&nbsp;




------------------ Original Message ------------------
From: "ossrs/srs" ***@***.***>;
Sent: May 14, 2022 (Saturday) 7:57 PM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject: Re: [ossrs/srs] Windows: Support cygwin 64bits (#2532)





  
That being said, have you ever compiled the Windows version? When I tried to compile it, I encountered two issues that prevented further execution...
 
First issue: ./config Building libsrtp-2-fit. patching file crypto/math/datatypes.c Reversed (or previously applied) patch detected! Assume -R? [n]
 
In this situation, I'm not sure how to handle it.
 
The second issue is: When making, in the file `src/app/srs_app_threads.cpp` at line 21, there is an error. In the file `src/app/srs_app_rtc_dtls.hpp` at line 16, there is a fatal error: `srtp2/srtp.h` file or directory does not exist. The compilation is terminated.
 
And here it ends.
     
During the SRS installation process, SRS will be added to the Windows environment variables, allowing users to directly launch SRS from the cmd console. 
If the system environment variables are not added, how can this be resolved? What variables should be manually added?
  
I also didn't add the environment variables. Does everyone use Windows? 
I have already given up and am waiting for future updates. Currently, I find CentOS more stable to use.
   
So, may I ask if you have ever compiled a Windows version? When I was compiling, I encountered two issues that prevented me from proceeding...
 
First issue: ./config
 Building libsrtp-2-fit.
 patching file crypto/math/datatypes.c
 Reversed (or previously applied) patch detected! Assume -R? [n]
 
This place, I don't know how to handle it?
 
The second one: when making.
 In file included from src/app/srs_app_threads.cpp:21:
 src/app/srs_app_rtc_dtls.hpp:16:10: fatal error: srtp2/srtp.h: No such file or directory
 16 | #include <srtp2/srtp.h&gt;
 | ^~~~~~~~~~~~~~
 compilation terminated.
 
That's the end here.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;

`TRANS_BY_GPT3`

**Comment by duliangheng** [comment]
> I have never compiled the Windows version before. The actual released version can run normally, but there are some differences in the command syntax between Linux and Windows. My problem at that time was that the conf file configured in Linux could not run properly in the Windows version. So I set up a local Linux server on an old computer with the help of Baota, which is very convenient. Why do you have to use Windows? I don't know what your application environment is, but I use the Linux version and it is very stable. I haven't made any changes since I set it up, and the speed is also good. Public network services can be directly deployed on the cloud, and lightweight servers are not expensive now. L.HF ***@***.*** Rongcheng Yijie Network Technology Co., Ltd.

I just want to learn because I rarely use Linux, so I want to use it on Windows.

`TRANS_BY_GPT3`

**Comment by puttys** [comment]
> > > > During the SRS installation process, SRS will be added to the Windows environment variables, allowing users to directly launch SRS from the cmd console.
> > > > What if the system environment variables are not added? How to manually add the variables?
> > > 
> > > 
> > > Mine also doesn't have the environment variables added? Does everyone use Windows?
> > > I have already given up and will wait for future updates. Currently, using CentOS is more stable.
> 
> Have you ever compiled a Windows version? When I was compiling, I encountered two issues that prevented me from proceeding...
> 
> First issue: ./config Building libsrtp-2-fit. patching file crypto/math/datatypes.c Reversed (or previously applied) patch detected! Assume -R? [n]
> 
> At this location, I don't know how to handle it.
> 
> Second: When making, in file included from src/app/srs_app_threads.cpp:21: src/app/srs_app_rtc_dtls.hpp:16:10: fatal error: srtp2/srtp.h: No such file or directory 16 | #include <srtp2/srtp.h> | ^~~~~~~~~~~~~~ compilation terminated.
> 
> This is the end.

> Manually compile 3rdparty\libsrtp-2-fit. Move the files under the include directory to objs\srtp2\include\srtp2. Move the compiled .a file to objs\srtp2\lib. Then run make again, it should work.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Already merged commit:

commit e9503a9c9a4055a52a114f857a44c8d041fb0c1c 
Author: wenjie.zhao <740936897@qq.com>
Date:   Fri Nov 18 23:02:35 2022 +0800

    For #2532: Windows: Replace ln by cp for windows. v5.0.87 (#3246)
    
    1. Replase ln by cp for windows.
    2. Refine OS and CPU arch detecting.
    3. Support configure from any directory by `SRS_WORKDIR`.
    4. Support output to any directory by `SRS_OUTPUT`.
    5. Disable sanitizer for gperf.
    6. Use parallels build for make.
    7. Refine bash variable check.

**Comment by winlinvip** [comment]
Known issue: Crash if enable SRT, the stack is:

```
gdb: unknown target exception 0x20474343 at 0x7fff993c039c

Thread 1 "srs" received signal ?, Unknown signal.
0x00007fff993c039c in RaiseException () from /cygdrive/c/Windows/System32/KERNELBASE.dll
(gdb) bt
#0  0x00007fff993c039c in RaiseException () from /cygdrive/c/Windows/System32/KERNELBASE.dll
#1  0x00000003ffc3cca1 in cyggcc_s-seh-1!_Unwind_RaiseException () from /usr/bin/cyggcc_s-seh-1.dll
#2  0x00000003ff20819b in cygstdc++-6!.cxa_throw () from /usr/bin/cygstdc++-6.dll
#3  0x00000001008c86c7 in CUDTUnited::accept(int, sockaddr*, int*) ()
#4  0x00000001008d17c2 in CUDT::accept(int, sockaddr*, int*) ()
#5  0x0000000100491d4c in SrsSrtSocket::accept (this=0x8000ed540, client_srt_fd=0x6fffff0afcb4) at ./src/protocol/srs_protocol_srt.cpp:757
#6  0x0000000100580360 in SrsSrtListener::cycle (this=0x8000e77b0) at ./src/app/srs_app_srt_listener.cpp:87
#7  0x00000001004ca5a9 in SrsFastCoroutine::cycle (this=0x8000fd360) at ./src/app/srs_app_st.cpp:285
#8  0x00000001004ca638 in SrsFastCoroutine::pfn (arg=0x8000fd360) at ./src/app/srs_app_st.cpp:300
#9  0x00000001005c6573 in _st_thread_main () at sched.c:371
#10 0x00000001005c6ee8 in st_thread_create (start=0x1, arg=0x18017c85d <dlcalloc+109>, joinable=16, stk_size=-14592) at sched.c:657
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

Build with SRT is ok, but it crashes while starting. Now we disable SRT by default as a workaround.
