### ISSUE TITLE
srs4.0.161编译后可以播放webrtc，4.0.191和198版本webrtc播放不了

### ISSUE THREAD

**Issue by lms0311** [ossrs/srs#2763]
> 注意：提问前，请先看FAQ(Please read FAQ before file an issue) https://github.com/ossrs/srs/issues/2716

**描述(Description)**

> 之前编译了4.0.161版本，rtc.conf配置好后，能用srs自带的网页播放rtc视频流，今天下载了最新的198版本编译后，rtc.conf没变，网页播放不了rtc视频流了，191版本同样播放不了，直到我把161版本编译好的srs可执行文件复制过来，才又能播放，161和191之间的版本没测试过

1. SRS版本(Version): `4.0.198`

1. SRS的配置如下(Config):
```

listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        file;
srs_log_file        ./objs/srs.log;

http_server {
    enabled         on;
    listen          9090;
    dir             ./objs/nginx/html;
}

http_api {
    enabled         on;
    listen          1985;
}
stats {
    network         0;
}
rtc_server {
    enabled on;
    # Listen at udp://8000
    listen 8000;
    #
    # The $CANDIDATE means fetch from env, if not configed, use * as default.
    #
    # The * means retrieving server IP automatically, from all network interfaces,
    # @see https://github.com/ossrs/srs/wiki/v4_CN_RTCWiki#config-candidate
    candidate 192.168.100.123;
}

vhost __defaultVhost__ {
    rtc {
        enabled     on;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
}

```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `xxxxxx`
1. `xxxxxx`
1. `xxxxxx`

**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)

**Comment by winlinvip** [comment]
Your question already exists in the FAQ, please search for `webrtc-live` in the FAQ: [#2716](https://github.com/ossrs/srs/issues/2716#webrtc-live)'

Make sure to maintain the markdown structure.

Before SRS 4.0.174, it was working, but after updating, it stopped working because `rtc.conf` does not enable RTMP to RTC by default. You need to use `rtmp2rtc.conf` or `rtc2rtmp.conf`, refer to 71ed6e5dc51df06eaa90637992731a7e75eabcd7.

Make sure to maintain the markdown structure.

`TRANS_BY_GPT3`
