### ISSUE TITLE
SrsCoroutine: pull() should be poll() ?

### ISSUE THREAD

**Issue by alongL** [ossrs/srs#2835]
在代码中有一些类中用到pull()函数， 是否命名为poll()更符合英文的原意？
用pull()，pull是拉取的意思，用到这个函数上感觉不是特别通顺。
linux里面有poll()函数被用来等待超时等操作，所以此处用poll的函数名更能表现此函数的意思？
或者就是应该用pull()，就是拉取的意思，只是我没有理解到？

```
class SrsCoroutine : public ISrsStartable
{
public:
    SrsCoroutine();
    virtual ~SrsCoroutine();
public:
    virtual void stop() = 0;
    virtual void interrupt() = 0;
    // @return a copy of error, which should be freed by user.
    //      NULL if not terminated and user should pull again.
    virtual srs_error_t pull() = 0;
    virtual const SrsContextId& cid() = 0;
};
```

**Comment by winlinvip** [comment]
The `pull()` is similar to [Go/Process.Status](https://pkg.go.dev/github.com/shirou/gopsutil/process#Process.Status), but it create(copy) an error if exists, so `get_status()` is not the proper word.

It also equals to python process [Process.is_alive](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Process.is_alive) and [Process.ProcessError](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.ProcessError), which check whether the process is alive and an detail error if terminated.

```
pull():err = is_alive():bool + copy_error():err
```

But it's too complex to use:

```
while (true) {
    if (!trd->is_alive() && (err = trd->copy_error()) != srs_success) {
        return err;
   }

   // Coroutine is alive, do some stuff.
}
```

Compare to the `pull()`, which means try to copy the error:

```
while (true) {
    if ((err = trd->pull()) != srs_success) {
        return err;
   }

   // Coroutine is alive, do some stuff.
}
```

1. User will free the `err`, because it's returned by `pull()`, similar to any common function.
2. Simple to use and maintain, to check the status and return if error.

If you get better word for this API, welcome to patch. 😄
