### ISSUE TITLE
gb28181接收rtp协程唤醒muxer协程的方式为什么不用srs_cond_signal?

### ISSUE THREAD

**Issue by yushimeng** [ossrs/srs#2874]
请问, gb28181 on_rtp的处理为什么没有使用srs_cond_signal(wait_ps_queue); 唤醒 rtmp_muxer的方式, 而是使用rtmp_muxer sleep的方式? 是有验证了唤醒的方式有性能问题还是出于别的考虑?
另外可能在倍速下载/播放的场景,可能sleep的间隔需要调整.

**Comment by winlinvip** [comment]
GB has been moved to a separate repository [srs-gb28181](https://github.com/ossrs/srs-gb28181), please refer to #2845.
For any issues, please submit them to the GB repository [bug](https://github.com/ossrs/srs-gb28181/issues), or [pr](https://github.com/ossrs/srs-gb28181/pulls).
Make sure to maintain the markdown structure.

Since 265 is mainly used in GB, the 265 branch has also been migrated to [srs-gb28181](https://github.com/ossrs/srs-gb28181/tree/feature/h265).
Make sure to maintain the markdown structure.

This issue will be deleted, please read the FAQ first: #2716.
Make sure to maintain the markdown structure.

`TRANS_BY_GPT3`
