### ISSUE TITLE
FEAT: log输出为json

### ISSUE THREAD

**Issue by jinleileiking** [ossrs/srs#2909]
目前的srs.log为文本，看看有没有需要输出为json，公司对回馈社区还是挺支持的，同意的话，我提一下

**Comment by winlinvip** [comment]
Welcome patch, refer to #2912

`TRANS_BY_GPT3`

**Comment by jinleileiking** [comment]
https://github.com/ossrs/srs/issues/2912 Is it sent wrong? It has nothing to do with the log.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Sorry, it is #2899 supporting Prometheus's API for troubleshooting implementation issues.

In troubleshooting, the main approach is to collect data through instrumentation like Prometheus, and then search for logs only when detailed logs are needed.

When searching for logs, the most suitable method is to use the grep command with the context ID. It is not suitable for JSON logs, but rather for text logs.

Generally, JSON-formatted logs are key logs for tracking, suitable for integration with Prometheus system, rather than directly converting all logs into JSON and filtering them.

Log troubleshooting is definitely necessary. I welcome discussing this solution and currently, I am more inclined towards using Prometheus with the current text log troubleshooting. Could you please look into it and see if it is suitable? I welcome your collaboration in implementing it.

`TRANS_BY_GPT3`
