### ISSUE TITLE
建议支持主备流

### ISSUE THREAD

**Issue by guoronghui** [ossrs/srs#2920]
为了提高推流的稳定性，大型直播一般会使用不同运营商的网络同时推送两个一样的流，不知道SSR是否支持主备流，当主流断流时，自动切换备用流，目前微信视频号支持主备流。

**Comment by ghostsf** [comment]
Hmm, not bad. The business application layer can also be implemented.

`TRANS_BY_GPT3`

**Comment by mapengfei53** [comment]
Does edge back-to-origin support backup source address to achieve this? For example, if the main address cannot find the stream, it will request from the backup address.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
It is entirely the responsibility of the business layer to do this. The encoder should push out two streams in order to have the significance of hot backup.

The encoder should not push one stream to SRS and let SRS forward two streams to the live platform on its own. This is because if SRS encounters any issues, both the primary and backup will be affected.

So the better approach is to have two encoders, each producing two streams, and send them to two different SRS instances, and then forward the streams to the live platform.

Perhaps someone might say, "In that case, we don't need to go through SRS, can't we just push directly to the platform?" Yes, pushing directly to the platform would work.

```
Encoder0 --Stream0---> Platform
Encoder1 --Stream1---> Platform
```

If you want to use SRS as a platform, you need SRS to support it. This is where the paradox arises: it is only used for large-scale live streaming, unless you want to use SRS to build your own CDN, there is no need to implement this feature. Therefore, SRS users don't actually have this requirement, at most they use SRS as the source station, and in this case, it can be implemented by the business system.

```
Encoder0 --Stream0---> SRS0 ---Stream0--> Platform
Encoder1 --Stream1---> SRS1 ---Stream1--> Platform
```

In your own business system, you can simply send the stream to the platform. After all, they are two independent SRS instances, and they are not even related to the source station cluster.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
SRS云服务器可以干这事，因为SRS云服务器就是业务层。我重新打开这个Issue吧。
