### ISSUE TITLE
K8s: Can't log to file even when config it. The srs_log_tank configuration is ineffective when deploying in K8s, it always outputs to the console.

### ISSUE THREAD

**Issue by ernestmeng** [ossrs/srs#3410]
> Note: Please read FAQ before file an issue, see #2716

## Description

When deploying SRS 5.0 on Kubernetes, the configuration is mounted using configMap. The configuration is effective, but the srs_log_tank configuration is not working and it always outputs to the console.

1. SRS Version: 5.0

2. SRS Log:
Some of the configMaps are as follows:
    <img width="412" alt="image" src="https://user-images.githubusercontent.com/48787106/218056924-ad0f340c-e483-4fb5-8935-fe2d3ba44180.png">
Enter the pod to view the mounted configuration information:
    <img width="472" alt="image" src="https://user-images.githubusercontent.com/48787106/218057643-dba062c9-867d-4b2c-aa40-ab32767d387e.png">
The configuration mounting is successful.
View the files in the objs directory:
    <img width="385" alt="image" src="https://user-images.githubusercontent.com/48787106/218057890-287ae20b-d8db-4427-9192-b933584e1010.png">
The srs.log file is not found. Use `kubectl logs` to view the startup logs.
    <img width="1511" alt="image" src="https://user-images.githubusercontent.com/48787106/218058769-19cef392-5b0e-41ea-8e10-b3fc23782790.png">
It is found that the logs are being written to the console, and the srs_log_tank configuration is not effective.

`TRANS_BY_GPT3`

**Comment by mapengfei53** [comment]
The configuration of 'srs_log_file' is missing a semicolon at the end.

`TRANS_BY_GPT3`

**Comment by mapengfei53** [comment]
麻烦发下你的Dockerfile文件，谢谢

**Comment by mapengfei53** [comment]
Please send me your Dockerfile file, thank you. If you are using the Dockerfile file provided with the code, please remove the environment variable configuration `SRS_SRS_LOG_TANK=console` from the file.
```
# Default workdir and command.
WORKDIR /usr/local/srs
ENV SRS_DAEMON=off
CMD ["./objs/srs", "-c", "conf/srs.conf"]
```

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Since by default everything in the container is directed to stdout, I made some changes to the Dockerfile and set the default value.

```dockerfile
ENV SRS_SRS_LOG_TANK=console SRS_DAEMON=off
```

You can override this environment variable by setting it when starting the container.

```bash
docker run --env SRS_SRS_LOG_TANK=file --rm -it ossrs/srs:5
```

You can also set it to empty, in which case the configuration from the configuration file will be used.

```bash
docker run --env SRS_SRS_LOG_TANK="" --rm -it ossrs/srs:5
```

Thanks to @mapengfei53 for troubleshooting.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Changed to a new environment variable: 

Since by default everything in the container is directed to stdout, I made some changes to the Dockerfile and set a default value:

```dockerfile
ENV SRS_LOG_TANK=console SRS_DAEMON=off
```

You can override this environment variable by setting it when starting the container.

```bash
docker run --env SRS_LOG_TANK=file --rm -it ossrs/srs:5
```

You can also set it to empty, in which case the configuration from the configuration file will be used.

```bash
docker run --env SRS_LOG_TANK="" --rm -it ossrs/srs:5
```

From version 5.0.142 onwards, and from version 6.0.25 onwards, please use the new environment variables in the future.

`TRANS_BY_GPT3`
