### ISSUE TITLE
The webvtt subtitles referenced by m3u8 cannot be displayed correctly on the client.

### ISSUE THREAD

**Issue by Wilbert0824** [ossrs/srs#3853]
**Describe the bug**
When playing m3u8 with streaming and subtitles, the streaming will play normally, but the subtitles cannot be displayed correctly. After logging, it was found that the client would continuously send subtitle requests to srs.

**Version**
5.0release (v5.0.193)

**To Reproduce**
1. Compile and launch from source code using clion.
2. Use OBS Studio to push the stream using RTMP (rtmp://localhost/live/livestream).
3. Set up m3u8 and put the webvtt file in /trunk/objs/nginx/html/live.
4. Use hls.js demo (https://tinyurl.com/yz72un3r), chrome extension (https://tinyurl.com/yxc5523r) or my video.js player to play index.m3u8.
5. After successful streaming, select the option to display subtitles.
6. See error.

**Expected behavior**
Play streaming and subtitles simultaneously.

**Additional context**
index.m3u8 (Generate by myself):
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="English",LANGUAGE="en",URI="sublist.m3u8"
#EXT-X-STREAM-INF:NAME="Main",SUBTITLES="subs"
livestream.m3u8

sublist.m3u8 (Generate by myself):
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:105
#EXTINF:70.817,
sub.webvtt

livestream.m3u8 (Generate by srs):
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:23
#EXT-X-TARGETDURATION:71
#EXTINF:70.833, no desc
livestream-0.ts
livestream-1.ts

**Comment by Wilbert0824** [comment]
Supplement:
Automatically add query after .webvtt

![2023-10-28_163246](https://github.com/ossrs/srs/assets/34716822/12035c43-2f87-404c-89bb-7fc402ebb210)

**Comment by winlinvip** [comment]
SRS does not support HLS with WebVTT subtitle, which is also not included in the RTMP specfication. And the source for generating subtitle is uncertain, meaning you can not add existing WebVTT file to a live stream, because in real world the live stream can not be described by fixed subtitle.

Now, with the ability and development in AI, it is now possible to generate subtitle automatically during live stream. This feature is supported by Oryx, not by SRS. Please refer to the transcript feature of Oryx, see [Revolutionizing Live Streams with AI Transcription: Creating Accessible, Multilingual Subtitles for Diverse Audiences](https://blog.ossrs.io/revolutionizing-live-streams-with-ai-transcription-creating-accessible-multilingual-subtitles-1e902ab856bd)
