### ISSUE TITLE
How to build SRS from scratch, from ubuntu:focal

### ISSUE THREAD

**Issue by bugsyb** [ossrs/srs#3918]
Hi,

Looking at Dockerfile, it uses ossrs/srs:ubuntu20 and this comes with number of binaries on top of standard ubuntu 20.04 (focal - LTS version).

SRS can be relatively easily compiled on such version by adding `build-essential autoconf tclsh cmake pkg-config`.

It fails later on trying to copy ffmpeg. 

Looking at ossrs/srs:ubuntu20 it includes number of versions whilst only one is copied.

Ask is - would you mind please to either provide Dockerfile used to build ossrs/srs:ubuntu20 or config options required to build ffmpeg (if not default).

Thanks!

**Comment by winlinvip** [comment]
I apologize for the confusion. In fact, the `ossrs/srs:ubuntu20` image is also open source. You can find the project here: https://github.com/ossrs/dev-docker/tree/ubuntu20.

Previously, we did not provide a link because this is a development environment, which people generally use directly without modifications. This development image is quite complex as it needs to support multiple platforms and cache all our dependencies, enabling us to achieve rapid compilation and verification during Pull Requests and Releases.

In fact, if you wish to use your own version of FFmpeg, you can modify your development image by copying your own FFmpeg into it. It is not strictly necessary to alter the development image itself.

To reiterate: You can refer to this project to implement the complete SRS toolchain on your own, if you are capable of handling its complexity. To my knowledge, most developers might not be interested in such an operational toolchain.

If you are willing to help us maintain these toolchains, you are also welcome to submit a Pull Request to this project.

`TRANS_BY_GPT4`
