### ISSUE TITLE
Closed - why?

### ISSUE THREAD

**Issue by misiek08** [ossrs/srs#575]
Hello!
Can you short describe why project is closed?
Can you tell if there's possibility to get source code? I downloaded repo each time I had to built code and have no copy on my PC...

It was such great project.... Thank you very much for it and I really hope you will keep doing great such like this one.

**Comment by Vavilen** [comment]
This is terrible news! What happened? The project is something wonderful!

**Comment by mbeacom** [comment]
@misiek08 https://github.com/mbeacom/srs  I forked it before the closure commit.

Anyway, thank you for everything, @winlinvip !
I am looking forward to go-oryx!

**Comment by amymayadi** [comment]
Thank you so much @Mark Beacom .
I appreciate your work!!
Hope @winlinvip could come back and join us soon.


2016-02-01 4:41 GMT+08:00 Mark Beacom notifications@github.com:


> @misiek08 https://github.com/misiek08 https://github.com/mbeacom/srs I
> forked it before the closure commit.
> 
> Anyway, thank you for everything, @winlinvip
> https://github.com/winlinvip !
> I am looking forward to go-oryx!
> 
> —' translates to '> —' in English.
> Reply to this email directly or view it on GitHub
> https://github.com/ossrs/srs/issues/575#issuecomment-177604296.


## 


马雅狄

QQ: 396130013
WeChat: MaAthenaDiana
Mail: Ma.athenadiana@gmail.com
CELL:+8613552793618


Yadi Ma
Non Linear Editing Software Research Center
China Digital Video.


Graduate University of Chinese Academy of Sciences


Email:ma.athenadiana@gmail.com
         mayadi06@mails.gucas.ac.cn
Phone: 0086 13552793618
HomePage:https://sites.google.com/site/amyyadima/Home

`TRANS_BY_GPT3`

**Comment by wenjiegit** [comment]
the new address of srs is https://github.com/wenjiegit/srs, which is cloned from this project.

**Comment by winlinvip** [comment]
I will list the main forks, if the owner want to continue the SRS project. 
If the owner of the branch wishes to maintain it, I will list out the branches that have been forked by many people.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@mbeacom Your fork is not the latest, please merge from @wenjiegit .

**Comment by misiek08** [comment]
@winlinvip can you write a short note about the reason you closed project? 
I still can't understand why you stopped such a great project :(

**Comment by winlinvip** [comment]
Reasons for SRS closure:
1. This is a false proposition. SRS is an open-source project and there is no concept of closure. Many forks are continuing its development. So the correct statement should be: SRS is no longer being updated.
2. Why is SRS no longer being updated? In fact, SRS is still being updated, but I am no longer updating it. On the homepage of SRS, there are three major fork branches that are actively being updated.
3. Why am I no longer updating SRS? This is the most accurate question and also the answer to the question. Why does it feel like SRS is dying if I'm not updating it? In reality, this is abnormal. We have been on the wrong path for a long time, so what's the point? Why does SRS stop updating when I stop updating it? In fact, this is where the problem lies.


Open source is not a one-person thing. I have already reached the limit of my abilities by releasing SRS versions 1 and 2. It is time to correct the mistakes. What is the right way? I don't know, but at least I will no longer continue with the wrong path.


Thanks~ 

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@misiek08 Maybe we should donate it to Apache org?

**Comment by winlinvip** [comment]
@mbeacom @wenjiegit @misiek08 Should we donate SRS to Apache org? And how to?

**Comment by wenjiegit** [comment]
I agree~

`TRANS_BY_GPT3`

**Comment by misiek08** [comment]
If you can help me I'll try to work on this project. Now I work on forked
module for nginx, but there are few big bugs and less functionality so it's
time to switch.

**Comment by misiek08** [comment]
@winlinvip I think, SRS should be kept without donating it to Apache, because many projects under Apache org just died because of inactivity.

**Comment by winlinvip** [comment]
@misiek08 I can add u to ossrs dev group. BTW, can u read Chinese, or English only?

**Comment by winlinvip** [comment]
@misiek08 I have invited u to the admin group of ossrs/srs, you have full access to srs now.
@wenjiegit @misiek08 Both of u are admin of srs now, the gitter channel for srs is open now, you can talk in it.

**Comment by mbeacom** [comment]
👍 Glad you guys are continuing the project!

**Comment by misiek08** [comment]
If it's possible it will be great to see new issues written in English,
because I totally don't understand Chinese and translating produces
unreadable text.

**Comment by winlinvip** [comment]
@misiek08 Please try to fix some issues and you can require the creator to describe the issue by English(I think everyone will glad to do this if you can help to fix the issue).

**Comment by winlinvip** [comment]
@misiek08 Please accept the invitation from https://github.com/orgs/ossrs to join the srs develop team.

**Comment by winlinvip** [comment]
Considering donating SRS to an open-source foundation to ensure the project remains open for approximately thirty years.

`TRANS_BY_GPT3`
