### ISSUE TITLE
How to stop SRS ? 

### ISSUE THREAD

**Issue by developeralp** [ossrs/srs#659]
I'm starting srs with : sudo /etc/init.d/srs start

I can close srs.

But when i close srs ,  nginx  is already running , i can access nginx via : http://localhost

Shortly : how can i close srs and nginx together ?

**Comment by winlinvip** [comment]
Nothing to do with SRS.

**Comment by jiangzhibin** [comment]
@developeralp 
If you build SRS by yourself, you can cd to "srs/trunk" directory.
stop srs: 		etc/init.d/srs stop
stop nginx:	 ./objs/nginx/sbin/nginx -s stop

start nginx: ./objs/nginx/sbin/nginx
start srs:     ./objs/srs -c conf/hls.conf   (you can also start with other *.conf file)
restart srs:  etc/init.d/srs restart

**Comment by quickstreamingmedia** [comment]
just do like this 
$ ps -A
find srs pid then 
$ kill -9 <pid srs>

thats it.

**Comment by developeralp** [comment]
thanks , @jiangzhibin @quickstreamingmedia solved :)

**Comment by winlinvip** [comment]
@jiangzhibin @alienmaster9 👍

**Comment by neilyoung** [comment]
There is no such a process on OSX. How to stop it there?

**Comment by neilyoung** [comment]
I see. It didn't start since it fails to:

[2022-03-31 23:36:38.684][Error][29888][36rt799a][0] invalid max_connections=1000, required=1107, system limit to 256, total=1007(max_connections=1000, nb_consumed_fds=7). you can change max_connections from 1000 to 248, or you can login as root and set the limit: ulimit -HSn 1107
[2022-03-31 23:36:38.684][Error][29888][36rt799a][0] Failed, code=1023 : check config : check connections : 1007 exceed max open files=256

**Comment by NeGitR** [comment]
> I see. It didn't start since it fails to:
> 
> [2022-03-31 23:36:38.684][Error][29888][36rt799a][0] invalid max_connections=1000, required=1107, system limit to 256, total=1007(max_connections=1000, nb_consumed_fds=7). you can change max_connections from 1000 to 248, or you can login as root and set the limit: ulimit -HSn 1107 [2022-03-31 23:36:38.684][Error][29888][36rt799a][0] Failed, code=1023 : check config : check connections : 1007 exceed max open files=256

Have the same issue, too.
