### ISSUE TITLE
对使用SRS做直播服务器有没有什么可适用的CDN服务可以推荐？

### ISSUE THREAD

**Issue by dhcn** [ossrs/srs#698]
如题。

**Comment by rhythmer** [comment]
upyun

**Comment by dhcn** [comment]
@rhythmer  不行，又拍云的云分发CDN功能根本不支持直播加速，只支持点播加速，虽然他也提供直播云服务，但是我是自己建立直播源站，只需要直播加速CDN服务。

**Comment by rhythmer** [comment]
你们如果有源站的话，可以选择反向代理的模式只通过他们的cdn分发直播流

On Tue, 22 Nov 2016 at 14:58 dhcn <notifications@github.com> wrote:

@rhythmer <https://github.com/rhythmer>
不行，又拍云的云分发CDN功能根本不支持直播加速，只支持点播加速，虽然他也提供直播云服务，但是我是自己建立直播源站，只需要直播加速CDN服务。

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ossrs/srs/issues/698#issuecomment-262162836>, or mute
the thread

**Comment by dhcn** [comment]
多谢推荐，虽说找到另外一个也支持RTMP播放流CDN服务，不过好东西不嫌多。我也贡献一个支持RTMP播放流的低价CDN:星云CDN，峰值价虽低，但是基本可以算是不支持按量收费。
