### ISSUE TITLE
HLS: inject meta data into the RTMP/DVR <-> HLS ID3 tags

### ISSUE THREAD

**Issue by k10pr0f** [ossrs/srs#754]
Hello @winlinvip !
Is it possible to inject timed meta data into the RTMP stream / save in DVR? 
Like how we can do in Wowza as described by this article:
https://www.wowza.com/forums/content.php?149-How-to-inject-cue-points-or-metadata&page=2
also, does srs support transforming these metatags into ID3 tags for transport inside a HLS stream?

I need this feature for save some events data on stream in DVR, and replay events from DVR file after stream ended.

p.s.
Thank you for a great project!

**Comment by winlinvip** [comment]
Well, there exists a way to inject metadata to RTMP or FLV stream, by inserting all cue points into the onMetadata RTMP packet or FLV tag. But it's not recommented, because it's realtime text messages, which should never be confused with A/V streaming packets. Maybe Adobe FMS/AMS mix the text and A/V messages together, but it's do a bad design and not compatible with CDN network or other archs. 
For example, do all CDN network support this? Absolutely no. Do all streaming protocols support this? Maybe not. Do all players support this? Nop, atleast Android H5 not support.
By conclusion, the text messages should never confused with A/V streaming messages, they must be delivery by different servers or clusters. SRS is used to delivery A/V streaming messages, there are  many realtime message system, for instance, kafka.

**Comment by ki0k1** [comment]
@winlinvip  Thank you for fast and great answer :)

**Comment by link89** [comment]
@winlinvip The AWS MediaLive server provide the capability. I guess if srs can provide the same capability it will be useful as a drop in replacement for MediaLive server.
