### ISSUE TITLE
FLV录制 session计划 仍然生成多个ts文件

### ISSUE THREAD

**Issue by troyz** [ossrs/srs#780]
我希望录制完成的时候能够合成一个 flv 文件。
但是最后发现生成了多个ts文件。（`path`/`segment`/`session`我都试过了）

| 参数项 | 参数值|
| - | - |
| srs版本 | `srs-2.0-b4`|
| OS | `osx` |
| config |      dvr {        enabled      on;<br/>        dvr_path     dvr_path     ./objs/nginx/html/[app]/[stream].[timestamp].flv;<br/>        dvr_plan     session;<br/>    }  |

请问怎样在录制结束时自动合成一个flv文件？

**Comment by winlinvip** [comment]
Session is this way, but it requires that your encoder cannot disconnect and re-push.
If your recording includes multiple streams, the server cannot give you a complete file because it doesn't know how many streams constitute one recording process.
If you use segments, you can specify a duration, for example, 30 minutes, and multiple streams within that duration will be written to one file. You can give it a try.

However, DVR itself is a rather complicated matter. The best approach is to use the segment method, for example, with a segment duration of 30 seconds. Then, using an HTTP callback, you can send these small segments to your system for processing (such as concatenation and transcoding). This way, it is faster than generating a complete DVR after the recording process (for example, for a 2-hour match, you can generate a file every 10 minutes, which is composed of multiple segments, and you can generate multiple files). All of these can be determined by your DVR system.

Additionally, if you create your own DVR, you can also support cloud storage.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Forgot to answer your original question:
1. A session itself is for streaming one file, there can be multiple sessions if you re-stream.
2. A segment will only exist for a certain period of time, but it requires correct time configuration. It becomes difficult to handle if the time is variable.
3. The best solution is to use segments and integrate with your own DVR system. This allows for multiple encodings and compatibility with various storage options, such as cloud storage.

`TRANS_BY_GPT3`

**Comment by ChandZhang** [comment]
Does using segment start counting from the time of generating the physical file? @winlin

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Multiple live streams can be combined into one file. You can consider using on_hls to merge HLS segments into one, based on your business requirements.

`TRANS_BY_GPT3`
