### ISSUE TITLE
HLS: 延迟删除切片，避免客户端访问失败

### ISSUE THREAD

**Issue by lzwjava** [ossrs/srs#781]
对话A： srs 中可不可能下载完 m3u8 列表时，开始下载第一个 ts，但因为服务端切割太快，已经把第一个ts删除了，导致读取失败呢。 srs 默认情况下只保存 m3u8 列表里的 ts，老的 ts 都立刻删除了。

对话B：默认删除ts切片，会不会出现：客户端下载完m3u8，开始下载ts的时候，发现服务端已经删了。

对话C：因为老的m3u8，跟服务端的不同步，所以老的m3u8 里存在老的ts。  服务器只保存新的m3u8里的ts，所以可能客户端取老的 ts 时，，服务端已经删除了，没有了。

不缓存的话回源压力会比较大。用上 CDN 可能会出这个问题。

希望有个能延时删除的选项。

hls_cleanup_timeout 60;

删除60秒之前的 ts 。

或者

hls_extra_remain_cnt 10;

多保留10个 ts。

**Comment by winlinvip** [comment]
For example, if there are 5 segments in an M3U8 file numbered 10-15, and a client tries to access segment 14 which is no longer in the M3U8 file, the following situations may occur:

1. If the access failure is due to delay, such as poor client network causing slow download speeds for segments 10-14 (obtained from the previous M3U8 refresh), the server may have already deleted segment 14 (or even segment 13 if the delay is longer). In this case, CDN re-sourcing or direct playback by the player will fail. Even if the deletion of segments is extended, it cannot solve this issue. The only solution is for the client to skip to the next available segment if the requested segment is missing. Of course, CDN usually has caching, so previous segments may still be available. However, if the edge server only has one player, the player itself will have to handle this situation.

2. If the access failure is due to boundary issues, such as some players always starting from the first segment and there is a delay before accessing the first segment (e.g., waiting for an advertisement), but the client's network is not a problem, then the delayed deletion strategy will be effective. As long as there are no further delays causing issues with subsequent segments.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Won't fix
