### ISSUE TITLE
Does V2.0 Support token parameter at the end of the url?

### ISSUE THREAD

**Issue by Azure4566** [ossrs/srs#942]
I saw in #741 that attaching the token to the end of the rtmp url should be supported, but when I tried something like rtmp://(my ip)/live/stream?token=XXXXX (The token is a jwt token), It seems that SRS regard the stream with and without token as different ones. Is this how it is for SRS V2.0?

**Comment by antonioparisi** [comment]
Hi @Azure4566,

I had the same issue in past. I made a patch to support the `param`.
Currently I'm using a fork of mine, since I raised a PR some time ago but it would have been merged on `develop` branch, that is still an experimental branch (future SRS v3.0).
I'm keeping as much as I can it up-to-date with any new commit that @winlinvip push over on the `2.0release` branch. So you can use it without any problem. Hope it helps.

https://github.com/antonioparisi/srs

**Comment by Azure4566** [comment]
Hi @antonioparisi 
Thanks for the reply, although I decided that I'll just modify my API server to work with token inserted in the middle of the url.
Anyway, really appreciate your help.
