### ISSUE TITLE
2.0.243 HTTP API未统计播放HLS的客户端

### ISSUE THREAD

**Issue by XiaoWind** [ossrs/srs#996]
RMTP的客户端能统计

**Comment by wnpllrzodiac** [comment]
hls, due to the multiple requests of m3u8 and ts, is different from the long connection of rtmp and flv protocols. It is estimated that it is not possible to count the number.

`TRANS_BY_GPT3`

**Comment by hping16** [comment]
I'm not very familiar with the HTTP protocol. Is there a field that corresponds to each client? If so, I can do the statistics myself.

`TRANS_BY_GPT3`

**Comment by wnpllrzodiac** [comment]
That requires the client to pass the session parameter, which is theoretically feasible. However, it requires cooperation from the client for development.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
If HLS is distributed through a regular HTTP server, it will not associate m3u8 and ts files, so the connection count is unknown. SRS3 can do this and improve the statistical information.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
SRS can act as an HLS origin server. When a client accesses it, for example, `http://ip/app/stream.m3u8`, by default it does not carry any identification information. In this case, the server will redirect with a 302 status code to a new address `http://ip/app/stream.m3u8?session=xxx`, creating a new session parameter. Additionally, this parameter will be included in each ts segment within the m3u8 file, allowing the server to track the number of online viewers.

The requirement is for the HTTP edge server to return a 302 status code to the client, instead of directly following the 302 redirection.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
This matter should be done at the edge, because if it is done at the origin server, each piece will have to be returned to the source, losing the function of HTTP edge.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
It may be done in SRS4. After enhancing the HTTP capability, it may be possible to track the number of HLS clients.

`TRANS_BY_GPT3`

**Comment by Wang-kk714** [comment]
> It may be done in SRS4. After enhancing the HTTP capability, it may be possible to count the number of HLS clients.

> Hello, I would like to ask if version 4.0 now supports HTTP API for HLS statistics?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
See https://github.com/ossrs/srs/issues/1657

**Comment by winlinvip** [comment]
Dup to #1657
